name: PublishAddon

on:
  push:
    branches:
      - releases/*

jobs:
  publish-addon:
    uses:  Pepperi-Addons/development-guidelines/.github/workflows/publish.yml@master
    secrets:
      PEPPERI_ADDON_PUBLISH_KEY: ${{ secrets.PEPPERI_ADDON_PUBLISH_KEY }}
  test-on-jenkins:
        needs: publish-addon 
        uses:  Pepperi-Addons/training-saar.g/.github/workflows/runJenkinsTests.yaml@main
        secrets:
            JENKINS_GITHUB_USER: ${{ secrets.JENKINS_GITHUB_USER }}
            JENKINS_GITHUB_TOKEN: ${{ secrets.JENKINS_GITHUB_TOKEN }}
            JENKINS_GITHUB_PASS: ${{ secrets.JENKINS_GITHUB_PASS }}
            JENKINS_GITHUB_JOB: ${{ secrets.JENKINS_GITHUB_JOB }}
            JENKINS_GITHUB_HOST: ${{ secrets.JENKINS_GITHUB_HOST }}